### ISSUE TITLE
0.1.1 doesn't build in nightly

### ISSUE THREAD

**Issue by o01eg** [bekker/msgbox-rs#3]
Building on Linux with rustc 1.36.0-dev (50a0defd5 2019-05-21) cause error:

```
Compiling glib v0.1.3
error[E0119]: conflicting implementations of trait `value::SetValueOptional` for type `&_`:
   --> /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.1.3/src/value.rs:509:1
    |
478 | impl<'a, T: ?Sized + SetValueOptional> SetValueOptional for &'a T {
    | ----------------------------------------------------------------- first implementation here
...
509 | impl<T: IsA<Object>> SetValueOptional for T {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `&_`
    |
    = note: downstream crates may implement trait `object::IsA<object::Object>` for type `&_`

error[E0119]: conflicting implementations of trait `value::SetValue` for type `&_`:
   --> /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.1.3/src/value.rs:503:1
    |
472 | impl<'a, T: ?Sized + SetValue> SetValue for &'a T {
    | ------------------------------------------------- first implementation here
...
503 | impl<T: IsA<Object>> SetValue for T {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `&_`
    |
    = note: downstream crates may implement trait `object::IsA<object::Object>` for type `&_`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0119`.
error: Could not compile `glib`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
It still build on stabe 1.34

**Comment by bekker** [comment]
Sorry I missed this. It seams OK with stable 1.37.0. Closing issue.

**Comment by HaraldRieder** [comment]
Strange. Today I started with Rust and GTK and I get this error with rustc 1.38.0 (625451e37 2019-09-23)

```
error[E0119]: conflicting implementations of trait `value::SetValueOptional` for type `&_`:
   --> /home/harald/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.1.3/src/value.rs:509:1
    |
478 | impl<'a, T: ?Sized + SetValueOptional> SetValueOptional for &'a T {
    | ----------------------------------------------------------------- first implementation here
...
509 | impl<T: IsA<Object>> SetValueOptional for T {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `&_`
    |
    = note: downstream crates may implement trait `object::IsA<object::Object>` for type `&_`

error[E0119]: conflicting implementations of trait `value::SetValue` for type `&_`:
   --> /home/harald/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.1.3/src/value.rs:503:1
    |
472 | impl<'a, T: ?Sized + SetValue> SetValue for &'a T {
    | ------------------------------------------------- first implementation here
...
503 | impl<T: IsA<Object>> SetValue for T {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `&_`
    |
    = note: downstream crates may implement trait `object::IsA<object::Object>` for type `&_`

error: aborting due to 2 previous errors
```

**Comment by HaraldRieder** [comment]
UPDATE: has nothing to do with rustc versions? I updated gtk dependency and now it compiles.

**Comment by bekker** [comment]
@HaraldRieder It indeed was gtk dependency problem, so new version - v0.2.0 -  was published on crates.io to resolve the issue. Did you get that error with the latest crate(v0.3.0)?
